# Generated by Django 4.2.11 on 2024-04-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20240403_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='auther',
            new_name='author',
        ),
    ]
