# Generated by Django 4.2.11 on 2024-04-26 02:05

import colorfield.fields
from django.db import migrations, models

import foodgram.constants


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0019_alter_cart_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default=foodgram.constants.default_color, image_field=None, max_length=25, samples=None),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('author', 'recipe'), name='unique_author_recipe'),
        ),
    ]
