version: '3.3'

volumes:
  pg_data:
  static_value:
  media_value:
  result_build:

services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
   image: maratlaischev/foodgram_backend
   restart: always
    # build:
    #   context: ../backend/foodgram/
    #   dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    env_file:
      - ../.env

  frontend:
   image: maratlaischev/foodgram_frontend
   restart: always
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "90:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
