# Generated by Django 3.2.16 on 2024-03-17 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientrecipe',
            name='volume',
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='measurement_unit',
            field=models.IntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredientrecipe',
            name='name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ingredient.ingredient', verbose_name='Ингредиент'),
            preserve_default=False,
        ),
    ]
