# Generated by Django 3.2.16 on 2024-03-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0004_auto_20240318_0410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='measurement_unit',
            new_name='volume',
        ),
    ]
