# Generated by Django 3.2.16 on 2024-03-19 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0005_rename_measurement_unit_ingredientrecipe_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingredient.ingredient', verbose_name='Ингредиент'),
        ),
    ]
