# Generated by Django 3.2.16 on 2024-03-19 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0006_alter_ingredientrecipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='volume',
            new_name='amount',
        ),
    ]
