# Generated by Django 3.2.16 on 2024-03-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0008_alter_ingredientrecipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='name',
            new_name='ingredient',
        ),
    ]
