# Generated by Django 3.2.16 on 2024-03-28 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_remove_recipe_ingredients'),
        ('ingredient', '0009_rename_name_ingredientrecipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Рецепт'),
            preserve_default=False,
        ),
    ]
