# Generated by Django 4.2.11 on 2024-04-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0012_alter_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'ингредиент', 'verbose_name_plural': 'Игредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'ингредиент рецепта', 'verbose_name_plural': 'Ингредиенты рецептов'},
        ),
    ]
