# Generated by Django 4.2.11 on 2024-04-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0014_alter_ingredientrecipe_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientRecipe',
        ),
    ]
