# Generated by Django 4.2.11 on 2024-04-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
