# Generated by Django 3.2.16 on 2024-03-28 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
